
name: pull-request

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: test
        shell: bash
        run: docker-compose run nayose bash /app/scripts/test.sh